import { Metadata } from "next"

export const metadata:Metadata = {
  title: {
    absolute:"", // use absolute to ignore templates defined in the parent layouts 
    default:"next js tut",
    template:"%s | next js tutorial"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header 
      style ={{backgroundColor:"lightblue",
        padding:"1rem"
      }}>
        <p>Header</p>
      </header>
      {children}
      <footer 
      style={{backgroundColor:"ghostwhite",
      padding:"1rem"
      }}>
        <p>footer</p>
      </footer>
        
      </body>
    </html>
  )
}
